version: '3.3'

services:
  ss-app:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${APP_USER}'
    container_name: "${APP_NAME}-app"
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "19003:9003"
    volumes:
      - ../:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
  ss-nginx:
    image: nginx:1.19-alpine
    container_name: "${APP_NAME}-nginx"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  ss-db:
    container_name: "${APP_NAME}-db"
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    ports:
      - "3307:3306"
  ss-mailhog:
    container_name: "${APP_NAME}-mailhog"
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
  ss-redis:
    image: redis:latest
    container_name: "${APP_NAME}-redis"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASS}
